name: compile-document

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v5

      - name: Install fonts ğŸ’¾
        run: |
          sudo apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer -y

      - name: Compile document ğŸ“„
        uses: xu-cheng/latex-action@v4
        with:
          root_file: memoria.tex
          latexmk_use_xelatex: true

      - name: Upload artifact ğŸ“¦
        uses: actions/upload-artifact@v5
        with:
          name: Memoria
          path: memoria.pdf
          overwrite: true