name: compile-document

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v5

      - name: Compile document ğŸ“”
        uses: docker://ghcr.io/qjoly/xelatex:latest
        with:
          args: memoria.tex

      - name: Upload artifact ğŸ“¦
        uses: actions/upload-artifact@v5
        with:
          name: Memoria
          path: memoria.pdf
          overwrite: true