name: compile-document

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v5

      - name: Compilar con XeLaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: memoria.tex
          latexmk_use_xelatex: true
          extra_system_packages: "msttcorefonts-installer"
          pre_compile: "update-ms-fonts && fc-cache -f"

      - name: Upload artifact ğŸ“¦
        uses: actions/upload-artifact@v5
        with:
          name: Memoria
          path: memoria.pdf
          overwrite: true